### ISSUE TITLE
Alternate save file location on Linux.

### ISSUE THREAD

**Issue by MJZ-31** [semilin/nine_saves#2]
I received the following error when trying to use the program.

![Screenshot from 2024-06-10 20-17-24](https://github.com/semilin/nine_saves/assets/116033542/0f87d1f3-3fba-47e5-bb85-f66ff72948c7)

Apparently some Steam installations for Linux store local files in ~/.steam rather than ~/.local/share/Steam. 
My full path was: ~/.steam/steam/steamapps/compatdata/1809540/pfx/drive_c/users/steamuser/AppData/LocalLow/RedCandleGames/NineSols

If anyone needs a temporary fix, creating a symlink seemed to do the trick:
```bash annotate
cd ~/.local/share
ln -s ~/.steam/steam ./Steam
```

**Comment by semilin** [comment]
Thanks for the report - this should be fixed now. The change will be included in the next release.
