### ISSUE TITLE
Mac os save file location

### ISSUE THREAD

**Issue by Mergemat** [semilin/nine_saves#5]
It is located in 
/Users/<user>/Library/Application\ Support/RedCandleGames/NineSols

<img width="246" alt="image" src="https://github.com/semilin/nine_saves/assets/38819496/a7d1e44f-9bb3-4f17-abed-6ebd9dd16f11">

hope this helps

**Comment by semilin** [comment]
Fixed in v0.1.3. Thanks for the report!
